/*
 * This source file was generated by the Gradle 'init' task
 */
package org.tictactoe;

public class App {
    public static void main(String[] args) {
        System.out.println("---WELCOME TO TICTACTOE---");

    }
}