/*
 * This source file was generated by the Gradle 'init' task
 */
package org.tictactoe;

import org.tictactoe.model.Board;
import org.tictactoe.model.Player;
import org.tictactoe.model.Symbol;
import org.tictactoe.strategy.RowColumnDiagonalStrategy;
import org.tictactoe.strategy.WinningStrategy;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println("---WELCOME TO TICTACTOE---");
        Scanner scn = new Scanner(System.in);
        Symbol selectedSymbol = null;
        List<Player> players = new ArrayList<>();
        for(int i=1; i<=2; i++) {
            System.out.println("Enter the name of player : " + i);
            String name = scn.nextLine().trim();
            System.out.println("Hello " + name + ", what symbol you want to choose? Here are few options:");
            System.out.println(Symbol.X);
            System.out.println(Symbol.O);
            System.out.println("Type X or O to choose:");
            Symbol symbol = chooseSymbol(scn, selectedSymbol);
            selectedSymbol = symbol;
            Player player = new Player(name, symbol);
            players.add(player);
        }

        Board board = new Board(3);
        WinningStrategy winningStrategy = new RowColumnDiagonalStrategy();
        Game game = new Game(board, players, winningStrategy);
    }

    private static Symbol chooseSymbol(Scanner scn, Symbol selectedSymbol) {
        String symbolInString = scn.nextLine().toUpperCase().trim();
        while(!(symbolInString.equals("X") || symbolInString.equals("O"))) {
            System.out.println("Your chosen symbol is not in the given options, please choose another symbol:");
            symbolInString = scn.nextLine().toUpperCase().trim();
        }
        Symbol symbol = Symbol.valueOf(symbolInString.toUpperCase());
        while(symbol == selectedSymbol) {
            System.out.println("Your chosen symbol is already taken, please choose another symbol:");
            symbolInString = scn.nextLine().toUpperCase().trim();
            symbol = Symbol.valueOf(symbolInString.toUpperCase());
        }

        return symbol;
    }
}